#pragma once

enum OBJID { OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_MONSTER_BULLET, OBJ_BOSS, OBJ_BOSS_BULLET, OBJ_END };
enum EVENTID { OBJ_EVENT_START, OBJ_EVENT_DEAD, OBJ_EVENT_END };
enum DIRECTION { RIGHT, LEFT, END };